### ISSUE TITLE
line 1, 2 of dump-foundobs.sql -- wrong path to zchecker.db?

### ISSUE THREAD

**Issue by Yeqzids** [mkelley/zbrowser#2]

**Comment by mkelley** [comment]
This could probably be made into a shell script that reads your zchecker.config, but obviously is not that right now.  You'll need to copy and edit it to use your database path.

**Comment by mkelley** [comment]
I've edited the README to help avoid this confusion.

**Comment by Yeqzids** [comment]
Duplicated of #3
